# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 13:16
from __future__ import unicode_literals

import common.fields
import common.state
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangoperm.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', djangoperm.db.fields.TextField(help_text='特定地址的名称', perms={'read': False, 'write': False}, verbose_name='地址名称')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', djangoperm.db.fields.CharField(help_text='城市的名称', max_length=90, perms={'read': False, 'write': False}, verbose_name='名称')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', djangoperm.db.fields.CharField(help_text='公司的名称', max_length=90, perms={'read': False, 'write': False}, verbose_name='名称')),
                ('tel', djangoperm.db.fields.CharField(default='', help_text='公司电话', max_length=32, perms={'read': False, 'write': False}, verbose_name='电话')),
                ('salable', djangoperm.db.fields.BooleanField(default=True, help_text='公司是否可被销售货物', perms={'read': False, 'write': False}, verbose_name='可销售状态')),
                ('purchasable', djangoperm.db.fields.BooleanField(default=False, help_text='是否可向公司采购', perms={'read': False, 'write': False}, verbose_name='可采购状态')),
                ('address', common.fields.ActiveLimitOneToOneField(blank=True, help_text='公司的所在地址,必须为公司对应合作伙伴的常用送货地址', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Address', verbose_name='公司地址')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(help_text='一对一绑定的相关django内置用户', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='绑定用户')),
                ('sex', djangoperm.db.fields.CharField(choices=[('unknown', '未知'), ('male', '男'), ('female', '女')], default='unknown', help_text='用户的性别', max_length=10, perms={'read': False, 'write': False}, verbose_name='性别')),
                ('phone', djangoperm.db.fields.CharField(default=None, help_text='用户唯一的移动电话', max_length=11, null=True, perms={'read': False, 'write': False}, unique=True, verbose_name='移动电话')),
                ('language', djangoperm.db.fields.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='zh-han', help_text='用户设置的默认语言', max_length=20, null=True, perms={'read': False, 'write': False}, verbose_name='语言')),
                ('mail_notice', djangoperm.db.fields.BooleanField(default=True, help_text='站内邮件提醒状态,为True时,实时提醒用户有未读的新邮件', perms={'read': False, 'write': False}, verbose_name='邮件提醒')),
                ('online_notice', djangoperm.db.fields.BooleanField(default=False, help_text='在线提醒状态,为True时,其他用户可以接收该用户的在线状态,并告知其下线', perms={'read': False, 'write': False}, verbose_name='在线提醒')),
                ('salable', djangoperm.db.fields.BooleanField(default=True, help_text='合作伙伴是否可被销售货物', perms={'read': False, 'write': False}, verbose_name='可销售状态')),
                ('purchasable', djangoperm.db.fields.BooleanField(default=False, help_text='是否可向合作伙伴采购', perms={'read': False, 'write': False}, verbose_name='可采购状态')),
                ('is_partner', djangoperm.db.fields.BooleanField(default=False, help_text='表示用户是否为合作伙伴', perms={'read': False, 'write': False}, verbose_name='是否为合作伙伴')),
                ('address', common.fields.ActiveLimitOneToOneField(blank=True, help_text='合作伙伴的所在地址', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Address')),
                ('default_send_address', common.fields.ActiveLimitForeignKey(blank=True, help_text='合作伙伴设置的默认送货地址', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_profiles', to='account.Address', verbose_name='默认地址')),
                ('usual_send_addresses', common.fields.ActiveLimitManyToManyField(blank=True, help_text='合作伙伴的常用送货地址', related_name='usual_profiles', to='account.Address', verbose_name='常用地址')),
            ],
            options={
                'verbose_name': '用户其他资料',
                'verbose_name_plural': '用户其他资料',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('country', djangoperm.db.fields.CharField(choices=[('China', '中国')], help_text='省份的所属国家', max_length=90, perms={'read': False, 'write': False}, verbose_name='国家')),
                ('name', djangoperm.db.fields.CharField(help_text='省份的名称', max_length=90, perms={'read': False, 'write': False}, verbose_name='名称')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', djangoperm.db.fields.CharField(help_text='地区的名称', max_length=90, perms={'read': False, 'write': False}, verbose_name='名称')),
                ('city', common.fields.ActiveLimitForeignKey(help_text='地区的所属城市', on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='account.City', verbose_name='城市')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together=set([('country', 'name')]),
        ),
        migrations.AddField(
            model_name='company',
            name='belong_users',
            field=common.fields.ActiveLimitManyToManyField(help_text='管理公司的人员', related_name='belong_companies', to=settings.AUTH_USER_MODEL, verbose_name='公司管理员'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_send_address',
            field=common.fields.ActiveLimitForeignKey(blank=True, help_text='公司设置的默认送货地址', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_companies', to='account.Address', verbose_name='默认送货地址'),
        ),
        migrations.AddField(
            model_name='company',
            name='usual_send_addresses',
            field=common.fields.ActiveLimitManyToManyField(help_text='公司的常用送货地址', related_name='usual_companies', to='account.Address', verbose_name='常用送货地址'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=common.fields.ActiveLimitForeignKey(help_text='城市的所属省份', on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='account.Province', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=common.fields.ActiveLimitForeignKey(help_text='地址的所属地区', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='account.Region', verbose_name='地区'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('city', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('name', 'address')]),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('province', 'name')]),
        ),
    ]
