# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 13:39
from __future__ import unicode_literals

from django.db import migrations
import djangoperm.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=djangoperm.db.fields.CharField(help_text='特定地址的名称', max_length=190, perms={'read': False, 'write': False}, verbose_name='地址名称'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('region', 'name')]),
        ),
    ]
