# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_notice',
            field=models.BooleanField(default=False, help_text='在线提醒状态,为True时,其他用户可以接收该用户的在线状态,并告知其下线', verbose_name='在线提醒'),
        ),
    ]
