# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_online_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(help_text='用户设置的默认语言', max_length=20, null=True, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mial_notice',
            field=models.BooleanField(default=True, help_text='站内邮件提醒状态,为True时,实时提醒用户有未读的新邮件', verbose_name='邮件提醒'),
        ),
    ]
