# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170507_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mial_notice',
            new_name='mail_notice',
        ),
    ]
