# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 13:23
from __future__ import unicode_literals

import common.fields
import common.state
from django.db import migrations, models
import django.db.models.deletion
import djangoperm.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170622_2123'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.AlterField(
            model_name='move',
            name='end_location',
            field=common.fields.LocationForeignKey(help_text='移动链的最终的库位', on_delete=django.db.models.deletion.PROTECT, related_name='converge_moves', to='stock.Location', verbose_name='最终库位'),
        ),
        migrations.AlterField(
            model_name='move',
            name='from_location',
            field=common.fields.LocationForeignKey(help_text='移动的起始库位', on_delete=django.db.models.deletion.PROTECT, related_name='out_moves', to='stock.Location', verbose_name='起始库位'),
        ),
        migrations.AlterField(
            model_name='move',
            name='initial_location',
            field=common.fields.LocationForeignKey(help_text='移动链的最初的库位', on_delete=django.db.models.deletion.PROTECT, related_name='spread_moves', to='stock.Location', verbose_name='初始库位'),
        ),
        migrations.AlterField(
            model_name='move',
            name='to_location',
            field=common.fields.LocationForeignKey(help_text='移动的结束库位', on_delete=django.db.models.deletion.PROTECT, related_name='in_moves', to='stock.Location', verbose_name='结束库位'),
        ),
        migrations.AlterField(
            model_name='path',
            name='from_location',
            field=common.fields.LocationForeignKey(help_text='产品从该库位移出', on_delete=django.db.models.deletion.PROTECT, related_name='out_paths', to='stock.Location', verbose_name='源库位'),
        ),
        migrations.AlterField(
            model_name='path',
            name='to_location',
            field=common.fields.LocationForeignKey(help_text='产品向该库位移入', on_delete=django.db.models.deletion.PROTECT, related_name='in_paths', to='stock.Location', verbose_name='目标库位'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='to_location',
            field=common.fields.LocationForeignKey(help_text='需求产生的库位', on_delete=django.db.models.deletion.PROTECT, to='stock.Location', verbose_name='库位'),
        ),
        migrations.AlterField(
            model_name='procurementfromlocationsettings',
            name='location',
            field=common.fields.LocationForeignKey(help_text='相关的位置', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_from_location_settings', to='stock.Location', verbose_name='来源位置'),
        ),
        migrations.AlterUniqueTogether(
            name='procurementdetail',
            unique_together=set([('procurement', 'product')]),
        ),
    ]
