# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 15:01
from __future__ import unicode_literals

import common.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_barcode'),
        ('stock', '0002_auto_20170622_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='root_node',
        ),
        migrations.AddField(
            model_name='move',
            name='lot',
            field=common.fields.ActiveLimitForeignKey(blank=True, default=None, help_text='产品所属的批次', null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Lot', verbose_name='批次'),
        ),
        migrations.AddField(
            model_name='procurementdetail',
            name='lot',
            field=common.fields.ActiveLimitForeignKey(blank=True, default=None, help_text='产品所属的批次', null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Lot', verbose_name='批次'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
