# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20170623_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='lot',
        ),
    ]
