# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 14:17
from __future__ import unicode_literals

import common.fields
from django.db import migrations
import django.db.models.deletion
import djangoperm.db.fields
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_move_lot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurement',
            options={'verbose_name': '需求', 'verbose_name_plural': '需求'},
        ),
        migrations.RemoveField(
            model_name='move',
            name='product',
        ),
        migrations.AddField(
            model_name='move',
            name='state',
            field=common.fields.SimpleStateCharField(choices=[('draft', '草稿'), ('confirmed', '已确定'), ('done', '已完成')], default=1, help_text='移动单的状态', max_length=10, perms={'read': False, 'write': False}, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetemplate',
            name='name',
            field=djangoperm.db.fields.CharField(default=1, help_text='包裹模板的名称', max_length=90, perms={'read': False, 'write': False}, unique=True, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurement',
            name='state',
            field=common.fields.SimpleStateCharField(choices=[('draft', '草稿'), ('confirmed', '已确定'), ('done', '已完成')], default=1, help_text='需求单的状态', max_length=10, perms={'read': False, 'write': False}, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='move',
            name='quantity',
            field=product.utils.QuantityField(decimal_places=12, help_text='产品的数量', max_digits=24, perms={'read': False, 'write': False}, uom='procurement_detail_setting.detail.product.uom', verbose_name='移动数量'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='self_location',
            field=common.fields.ActiveLimitOneToOneField(help_text='区域的基本位置', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_zone', to='stock.Location', verbose_name='库位'),
        ),
    ]
