# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20170626_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quant',
        ),
    ]
