# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangoperm.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_delete_quant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'verbose_name': '移动', 'verbose_name_plural': '移动'},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='parent_location',
            new_name='parent_node',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='self_location',
        ),
        migrations.AddField(
            model_name='location',
            name='index',
            field=djangoperm.db.fields.CharField(blank=True, default='', help_text='该包裹所在包裹树的索引', max_length=190, perms={'read': False, 'write': False}, verbose_name='索引'),
        ),
        migrations.AddField(
            model_name='location',
            name='level',
            field=djangoperm.db.fields.PositiveSmallIntegerField(default=0, help_text='该包裹所距离所在包裹树的根的距离', perms={'read': False, 'write': False}, verbose_name='树层'),
        ),
        migrations.AlterField(
            model_name='move',
            name='procurement_detail_setting',
            field=models.ForeignKey(help_text='生成该移动的需求明细设置', on_delete=django.db.models.deletion.CASCADE, to='stock.ProcurementFromLocationSettings', verbose_name='需求明细设置'),
        ),
        migrations.AlterField(
            model_name='packagenode',
            name='parent_node',
            field=models.ForeignKey(default=None, help_text='该节点的父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='stock.PackageNode', verbose_name='父节点'),
        ),
    ]
