# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 13:16
from __future__ import unicode_literals

import common.fields
import common.state
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djangoperm.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', djangoperm.db.fields.CharField(help_text='产品属性的名称', max_length=190, perms={'read': False, 'write': False}, verbose_name='名称')),
                ('value', djangoperm.db.fields.JSONField(help_text='JSON格式保存的属性可选值', json_type='list', perms={'read': False, 'write': False}, verbose_name='值')),
            ],
            options={
                'verbose_name': '属性',
                'verbose_name_plural': '属性',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('attributes', djangoperm.db.fields.JSONField(blank=True, default={}, help_text='根据产品模板的属性列表设置的产品属性值字典', json_type='dict', perms={'read': False, 'write': False}, verbose_name='产品属性字典')),
                ('in_code', djangoperm.db.fields.CharField(blank=True, help_text='产品模板的内部编码', max_length=190, perms={'read': False, 'write': False}, verbose_name='内部编码')),
                ('out_code', djangoperm.db.fields.CharField(blank=True, help_text='产品模板的外部编码', max_length=190, perms={'read': False, 'write': False}, verbose_name='外部编码')),
                ('weight', djangoperm.db.fields.DecimalField(blank=True, decimal_places=12, default=Decimal('0.0'), help_text='产品的重量,单位为kg', max_digits=24, perms={'read': False, 'write': False}, verbose_name='重量')),
                ('volume', djangoperm.db.fields.DecimalField(blank=True, decimal_places=12, default=Decimal('0.0'), help_text='产品的体积,单位为m³', max_digits=24, perms={'read': False, 'write': False}, verbose_name='体积')),
                ('salable', djangoperm.db.fields.BooleanField(default=False, help_text='商品的销售状态,如果为False则不能被销售', perms={'read': False, 'write': False}, verbose_name='销售状态')),
                ('purchasable', djangoperm.db.fields.BooleanField(default=False, help_text='商品的采购状态,如果为False则不能被采购', perms={'read': False, 'write': False}, verbose_name='采购状态')),
                ('rentable', djangoperm.db.fields.BooleanField(default=False, help_text='商品的租借状态,如果为False则不能通过被租借', perms={'read': False, 'write': False}, verbose_name='租借状态')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', djangoperm.db.fields.CharField(help_text='产品的种类', max_length=90, perms={'read': False, 'write': False}, unique=True, verbose_name='种类名称')),
                ('sequence', djangoperm.db.fields.PositiveIntegerField(blank=True, default=0, help_text='产品种类的排序', perms={'read': False, 'write': False}, verbose_name='排序')),
            ],
            options={
                'verbose_name': ('产品分类',),
                'verbose_name_plural': '产品分类',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', djangoperm.db.fields.CharField(help_text='产品模板的名称', max_length=190, perms={'read': False, 'write': False}, unique=True, verbose_name='名称')),
                ('sequence', djangoperm.db.fields.PositiveIntegerField(blank=True, default=0, help_text='产品显示的排序', perms={'read': False, 'write': False}, verbose_name='排序')),
                ('detail', djangoperm.db.fields.CharField(blank=True, default='', help_text='产品的提示', max_length=190, perms={'read': False, 'write': False}, verbose_name='提示')),
                ('in_description', djangoperm.db.fields.TextField(blank=True, default='', help_text='产品内部的说明', perms={'read': False, 'write': False}, verbose_name='内部说明')),
                ('out_description', djangoperm.db.fields.TextField(blank=True, default='', help_text='产品的外部说明', perms={'read': False, 'write': False}, verbose_name='外部说明')),
                ('attributes', common.fields.ActiveLimitManyToManyField(help_text='产品模板的默认属性', to='product.Attribute', verbose_name='默认属性')),
                ('category', models.ForeignKey(blank=True, help_text='产品的分类', null=True, on_delete=django.db.models.deletion.PROTECT, to='product.ProductCategory', verbose_name='产品种类')),
            ],
            options={
                'verbose_name': '产品模板',
                'verbose_name_plural': '产品模板',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', djangoperm.db.fields.CharField(help_text='单位名称', max_length=20, perms={'read': False, 'write': False}, unique=True, verbose_name='名称')),
                ('symbol', djangoperm.db.fields.CharField(help_text='单位符号', max_length=10, perms={'read': False, 'write': False}, unique=True, verbose_name='符号')),
                ('decimal_places', djangoperm.db.fields.PositiveSmallIntegerField(default=3, help_text='数量转为浮点数显示时,数量的小数个数', perms={'read': False, 'write': False}, verbose_name='小数精度')),
                ('round_method', djangoperm.db.fields.CharField(choices=[('ROUND_CEILING', '趋向无穷大取整'), ('ROUND_DOWN', '趋向零取整'), ('ROUND_FLOOR', '趋向负无穷大取整'), ('ROUND_HALF_DOWN', '末位大于五反向零取整,否则趋向零取整'), ('ROUND_HALF_EVEN', '末位大于五反向零取整,小于五趋向零取整,遇五前位为奇数反向零取整'), ('ROUND_HALF_UP', '末位大于等于五反向零取整,否则趋向零取整'), ('ROUND_UP', '反向零取整'), ('ROUND_05UP', '取整位数为零或五时反向零取整,否则趋向零取整')], default='ROUND_CEILING', help_text='根据单位做精度转换时单位的默认舍入方法', max_length=10, perms={'read': False, 'write': False}, verbose_name='舍入方法')),
                ('ratio_type', djangoperm.db.fields.CharField(choices=[('greater', '大于'), ('smaller', '小于'), ('equal', '等于')], default='greater', help_text='单位与主单位的比较方式', max_length=10, perms={'read': False, 'write': False}, verbose_name='比率类型')),
                ('ratio', djangoperm.db.fields.DecimalField(decimal_places=12, help_text='与对应单位类型的标准单位的比值', max_digits=24, perms={'read': False, 'write': False}, verbose_name='比率')),
                ('category', djangoperm.db.fields.CharField(choices=[('m', '米'), ('kg', '千克'), ('s', '秒'), ('A', '安培'), ('K', '开尔文'), ('J', '焦耳'), ('m²', '平方米'), ('m³', '立方米'), ('unit', '个'), ('yuan', '元')], help_text='单位所属的单位类型,仅当单位属于同一类型时,方可互相转换', max_length=5, perms={'read': False, 'write': False}, verbose_name='单位类型')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='uom',
            field=common.fields.ActiveLimitForeignKey(help_text='产品的默认计量单位', on_delete=django.db.models.deletion.PROTECT, to='product.UOM', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='product',
            name='template',
            field=common.fields.ActiveLimitForeignKey(help_text='产品的模板', on_delete=django.db.models.deletion.PROTECT, to='product.ProductTemplate', verbose_name='模板'),
        ),
    ]
