# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 13:23
from __future__ import unicode_literals

import common.fields
import common.state
from django.db import migrations, models
import django.db.models.deletion
import djangoperm.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', djangoperm.db.fields.CharField(help_text='批次的名称', max_length=90, perms={'read': False, 'write': False}, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '批次',
                'verbose_name': '批次',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': '产品分类', 'verbose_name_plural': '产品分类'},
        ),
        migrations.AddField(
            model_name='product',
            name='attributes_md5',
            field=djangoperm.db.fields.CharField(default=1, help_text='产品属性字典json值的md5值', max_length=40, perms={'read': False, 'write': False}, verbose_name='产品属性字典的md5值'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=djangoperm.db.fields.CharField(help_text='产品属性的名称', max_length=190, perms={'read': False, 'write': False}, unique=True, verbose_name='名称'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('template', 'attributes_md5')]),
        ),
        migrations.AddField(
            model_name='lot',
            name='product',
            field=common.fields.ActiveLimitForeignKey(help_text='批次相关的产品', on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品'),
        ),
    ]
