# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 15:01
from __future__ import unicode_literals

import common.fields
import common.state
from django.db import migrations, models
import django.db.models.deletion
import djangoperm.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170622_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('mode', djangoperm.db.fields.CharField(choices=[('Standard39', '标准39')], help_text='条形码模式', max_length=20, perms={'read': False, 'write': False}, verbose_name='条形码模式')),
                ('code', djangoperm.db.fields.JSONField(help_text='条形码的编码值字典', json_type='dict', perms={'read': False, 'write': False}, verbose_name='条形码编码值')),
                ('have_quiet', djangoperm.db.fields.BooleanField(default=False, help_text='条形码是否还有空白区', perms={'read': False, 'write': False}, verbose_name='是否含有静区')),
                ('is_iso_scale', djangoperm.db.fields.BooleanField(default=False, help_text='条形码是否已被iso标准收录', perms={'read': False, 'write': False}, verbose_name='是否被iso收录')),
                ('check_sum', djangoperm.db.fields.BooleanField(default=False, help_text='条形码是否检查合计', perms={'read': False, 'write': False}, verbose_name='是否检查合计')),
                ('product', common.fields.ActiveLimitOneToOneField(help_text='条形码对应的产品', on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.state.StateMachine),
        ),
    ]
