# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 09:07
from __future__ import unicode_literals

import common.state
from django.db import migrations, models
import django.db.models.deletion
import django_perm.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', django_perm.db.fields.BooleanField(default=True, help_text='the status of active,True means active,False means not active', perms={'read': False, 'write': False}, verbose_name='status of active')),
                ('is_delete', django_perm.db.fields.BooleanField(default=False, help_text='the status of delete,True means have been deleted,False means have not be deleted', perms={'read': False, 'write': False}, verbose_name='status of delete')),
                ('create_time', django_perm.db.fields.DateTimeField(auto_now_add=True, help_text='will auto write when create this node', perms={'read': False, 'write': False}, verbose_name='create time')),
                ('last_modify_time', django_perm.db.fields.DateTimeField(auto_now=True, help_text='will auto write time when create or modify this node', perms={'read': False, 'write': False}, verbose_name='last modify time')),
                ('name', django_perm.db.fields.CharField(help_text='the name of the address', max_length=190, perms={'read': False, 'write': False}, verbose_name='name')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_perm.db.fields.CharField(help_text='the name of city', max_length=90, perms={'read': False, 'write': False}, verbose_name='name')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_perm.db.fields.CharField(choices=[('China', 'China')], help_text="province's country", max_length=90, perms={'read': False, 'write': False}, verbose_name='country')),
                ('name', django_perm.db.fields.CharField(help_text='the name of province', max_length=90, perms={'read': False, 'write': False}, verbose_name='name')),
            ],
            options={
                'verbose_name': 'province',
                'verbose_name_plural': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_perm.db.fields.CharField(help_text='the name of region', max_length=90, perms={'read': False, 'write': False}, verbose_name='name')),
                ('city', models.ForeignKey(help_text='the city of the region', on_delete=django.db.models.deletion.CASCADE, to='django_base.City', verbose_name='city')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'region',
            },
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together=set([('country', 'name')]),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(help_text='the province of the city', on_delete=django.db.models.deletion.CASCADE, to='django_base.Province', verbose_name='province'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(help_text='the region of the address', on_delete=django.db.models.deletion.CASCADE, to='django_base.Region', verbose_name='region'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('city', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('province', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('region', 'name')]),
        ),
    ]
