# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:07
from __future__ import unicode_literals

import apps.account.utils
import apps.djangoperm.db.fields
import apps.product.utils
import apps.stock.utils
import common.fields
import common.state
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', apps.djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', apps.djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', apps.djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', apps.djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('index', apps.djangoperm.db.fields.CharField(blank=True, default='', help_text='该包裹所在包裹树的索引', max_length=190, perms={'read': False, 'write': False}, verbose_name='索引')),
                ('level', apps.djangoperm.db.fields.PositiveSmallIntegerField(default=0, help_text='该包裹所距离所在包裹树的根的距离', perms={'read': False, 'write': False}, verbose_name='树层')),
                ('is_virtual', apps.djangoperm.db.fields.BooleanField(default=False, help_text='库位的虚拟状态', perms={'read': False, 'write': False}, verbose_name='虚拟库位')),
                ('x', apps.djangoperm.db.fields.CharField(blank=True, help_text='库位的X轴坐标', max_length=90, perms={'read': False, 'write': False}, verbose_name='X')),
                ('y', apps.djangoperm.db.fields.CharField(blank=True, help_text='库位的Y轴坐标', max_length=90, perms={'read': False, 'write': False}, verbose_name='Y')),
                ('z', apps.djangoperm.db.fields.CharField(blank=True, help_text='库位的Z轴坐标', max_length=90, perms={'read': False, 'write': False}, verbose_name='Z')),
                ('parent_node', common.fields.ActiveLimitForeignKey(blank=True, help_text='库位所属的上级库位,若库位为区域的基本库位,则必须为虚拟库位', null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.Location', verbose_name='上级库位')),
            ],
            options={
                'verbose_name': '库位',
                'verbose_name_plural': '库位',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', apps.djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', apps.djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', apps.djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', apps.djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('quantity', apps.product.utils.QuantityField(decimal_places=12, help_text='产品的数量', max_digits=24, perms={'read': False, 'write': False}, uom='procurement_detail.product.template.uom', verbose_name='移动数量')),
                ('state', common.fields.SimpleStateCharField(choices=[('draft', '草稿'), ('confirmed', '已确定'), ('done', '已完成')], default='draft', help_text='移动单的状态', max_length=10, perms={'read': False, 'write': False}, verbose_name='状态')),
                ('end_location', apps.stock.utils.LocationForeignKey(help_text='移动链的最终的库位', on_delete=django.db.models.deletion.PROTECT, related_name='converge_moves', to='stock.Location', verbose_name='最终库位')),
                ('from_location', apps.stock.utils.LocationForeignKey(help_text='移动的起始库位', on_delete=django.db.models.deletion.PROTECT, related_name='out_moves', to='stock.Location', verbose_name='起始库位')),
                ('initial_location', apps.stock.utils.LocationForeignKey(help_text='移动链的最初的库位', on_delete=django.db.models.deletion.PROTECT, related_name='spread_moves', to='stock.Location', verbose_name='初始库位')),
            ],
            options={
                'verbose_name': '移动',
                'verbose_name_plural': '移动',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='PackageNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', apps.djangoperm.db.fields.CharField(blank=True, default='', help_text='该包裹所在包裹树的索引', max_length=190, perms={'read': False, 'write': False}, verbose_name='索引')),
                ('level', apps.djangoperm.db.fields.PositiveSmallIntegerField(default=0, help_text='该包裹所距离所在包裹树的根的距离', perms={'read': False, 'write': False}, verbose_name='树层')),
                ('name', apps.djangoperm.db.fields.CharField(help_text='打包方法的名称', max_length=90, perms={'read': False, 'write': False}, unique=True, verbose_name='名称')),
                ('quantity', apps.djangoperm.db.fields.PositiveSmallIntegerField(default=1, help_text='包裹的数量', perms={'read': False, 'write': False}, verbose_name='数量')),
                ('parent_node', models.ForeignKey(default=None, help_text='该节点的父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='stock.PackageNode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '包裹节点',
                'verbose_name_plural': '包裹节点',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', apps.djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', apps.djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', apps.djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', apps.djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', apps.djangoperm.db.fields.CharField(help_text='包裹模板的名称', max_length=90, perms={'read': False, 'write': False}, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '包裹模板',
                'verbose_name_plural': '包裹模板',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='PackageTemplateProductSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', apps.product.utils.QuantityField(decimal_places=12, help_text='包裹模板包含该产品的数量', max_digits=24, perms={'read': False, 'write': False}, uom='product.template.uom', verbose_name='最大数量')),
                ('package_template', common.fields.ActiveLimitForeignKey(help_text='相关的包裹模板', on_delete=django.db.models.deletion.PROTECT, related_name='template_settings', to='stock.PackageTemplate', verbose_name='包裹模板')),
            ],
            options={
                'verbose_name': '包裹模板产品设置',
                'verbose_name_plural': '包裹模板产品设置',
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', apps.djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', apps.djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', apps.djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', apps.djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', apps.djangoperm.db.fields.CharField(help_text='包裹类型的名称', max_length=90, perms={'read': False, 'write': False}, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '包裹类型',
                'verbose_name_plural': '包裹类型',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='PackageTypeProductSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_quantity', apps.product.utils.QuantityField(decimal_places=12, help_text='包裹类型能够包含该产品的最大数量', max_digits=24, perms={'read': False, 'write': False}, uom='product.template.uom', verbose_name='最大数量')),
                ('package_type', common.fields.ActiveLimitForeignKey(help_text='相关的包裹类型', on_delete=django.db.models.deletion.PROTECT, related_name='type_settings', to='stock.PackageType', verbose_name='包裹类型')),
                ('product', common.fields.ActiveLimitForeignKey(help_text='相关的产品', on_delete=django.db.models.deletion.PROTECT, related_name='type_settings', to='product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '包裹类型产品设置',
                'verbose_name_plural': '包裹类型产品设置',
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', apps.djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', apps.djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', apps.djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', apps.djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('is_return', apps.djangoperm.db.fields.BooleanField(default=False, help_text='需求的退货状态,若改需求为退货需求,则为True', perms={'read': False, 'write': False}, verbose_name='退货状态')),
                ('state', common.fields.CancelableSimpleStateCharField(choices=[('draft', '草稿'), ('confirmed', '已确定'), ('done', '已完成'), ('cancel', '取消')], default='draft', help_text='需求单的状态', max_length=10, perms={'read': False, 'write': False}, verbose_name='状态')),
                ('address', common.fields.ActiveLimitForeignKey(help_text='客户要求到达的送货地址', on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='account.Address', verbose_name='送货地址')),
                ('return_procurement', common.fields.ActiveLimitOneToOneField(blank=True, help_text='产生退货时,需求对应的退货需求', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_procurement', to='stock.Procurement', verbose_name='退货需求')),
                ('to_location', apps.stock.utils.LocationForeignKey(help_text='需求产生的库位', on_delete=django.db.models.deletion.PROTECT, to='stock.Location', verbose_name='库位')),
                ('user', apps.account.utils.PartnerForeignKey(help_text='提出需求的相关合作伙伴', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='合作伙伴')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='ProcurementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', apps.product.utils.QuantityField(decimal_places=12, help_text='产品的数量', max_digits=24, perms={'read': False, 'write': False}, uom='product.template.uom', verbose_name='数量')),
                ('lot', common.fields.ActiveLimitForeignKey(blank=True, default=None, help_text='产品所属的批次', null=True, on_delete=django.db.models.deletion.PROTECT, to='product.Lot', verbose_name='批次')),
                ('procurement', common.fields.ActiveLimitForeignKey(help_text='需求明细所属的需求', on_delete=django.db.models.deletion.PROTECT, related_name='details', to='stock.Procurement', verbose_name='需求')),
                ('product', common.fields.ActiveLimitForeignKey(help_text='明细相关的产品', on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '需求明细',
                'verbose_name_plural': '需求明细',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', apps.djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', apps.djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', apps.djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', apps.djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', apps.djangoperm.db.fields.CharField(help_text='路线的名称', max_length=190, perms={'read': False, 'write': False}, unique=True, verbose_name='名称')),
                ('sequence', apps.djangoperm.db.fields.PositiveSmallIntegerField(default=0, help_text='在相同起始库位和终点库位的路线的优先级', perms={'read': False, 'write': False}, verbose_name='优先级')),
                ('end_location', common.fields.ActiveLimitForeignKey(blank=True, help_text='路线的终点库位', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_routes', to='stock.Location', verbose_name='终点库位')),
                ('initial_location', common.fields.ActiveLimitForeignKey(blank=True, help_text='路线的起始库位', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_routes', to='stock.Location', verbose_name='起始库位')),
            ],
            options={
                'verbose_name': '路线',
                'verbose_name_plural': '路线',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='RouteLocationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', apps.djangoperm.db.fields.PositiveSmallIntegerField(default=0, help_text='路径设置的排序', perms={'read': False, 'write': False}, verbose_name='排序')),
                ('location', common.fields.ActiveLimitForeignKey(help_text='路径设置所设置的路径', on_delete=django.db.models.deletion.PROTECT, related_name='route_location_settings', to='stock.Location', verbose_name='路径')),
                ('route', common.fields.ActiveLimitForeignKey(help_text='路径设置所属的路线', on_delete=django.db.models.deletion.PROTECT, related_name='route_location_settings', to='stock.Route', verbose_name='路线')),
            ],
            options={
                'verbose_name': '路线的路径配置',
                'verbose_name_plural': '路线的路径配置',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', apps.djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', apps.djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', apps.djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', apps.djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('name', apps.djangoperm.db.fields.CharField(help_text='仓库的名称', max_length=90, perms={'read': False, 'write': False}, verbose_name='名称')),
                ('address', common.fields.ActiveLimitForeignKey(help_text='仓库的地理位置', on_delete=django.db.models.deletion.PROTECT, to='account.Address', verbose_name='地址')),
                ('user', apps.account.utils.PartnerForeignKey(help_text='仓库的相关合作伙伴或联系人', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='联系人')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', apps.djangoperm.db.fields.BooleanField(default=True, help_text='记录的可用状态,False为不可用,True为可用', perms={'read': False, 'write': False}, verbose_name='可用状态')),
                ('is_delete', apps.djangoperm.db.fields.BooleanField(default=False, help_text='记录的删除状态,True删除不可视,False为尚未删除', perms={'read': False, 'write': False}, verbose_name='删除状态')),
                ('create_time', apps.djangoperm.db.fields.DateTimeField(auto_now_add=True, help_text='记录的创建时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='创建时间')),
                ('last_modify_time', apps.djangoperm.db.fields.DateTimeField(auto_now=True, help_text='记录的最后修改时间,UTC时间', perms={'read': False, 'write': False}, verbose_name='最后修改时间')),
                ('usage', apps.djangoperm.db.fields.CharField(choices=[('stock', '仓库'), ('pick', '分拣流程区域'), ('check', '验货流程区域'), ('pack', '包裹流程区域'), ('wait', '物流等待流程区域'), ('deliver', '物流运输流程区域'), ('customer', '顾客区域'), ('supplier', '供应商区域'), ('produce', '生产区域'), ('repair', '返工维修区域'), ('scrap', '报废区域'), ('closeout', '平仓区域'), ('initial', '初始区域'), ('midway', '中途岛区域')], default='container', help_text='区域的用途', max_length=30, perms={'read': False, 'write': False}, verbose_name='用途')),
                ('root_location', common.fields.ActiveLimitForeignKey(blank=True, help_text='代表区域本身的根库位', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_zone', to='stock.Location', verbose_name='根节点')),
                ('warehouse', common.fields.ActiveLimitForeignKey(help_text='区域所属的仓库', on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='stock.Warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
            },
            bases=(models.Model, common.state.StateMachine),
        ),
        migrations.AddField(
            model_name='route',
            name='locations',
            field=models.ManyToManyField(help_text='路线的详细路径', related_name='routes', through='stock.RouteLocationSetting', to='stock.Location', verbose_name='路径'),
        ),
        migrations.AddField(
            model_name='route',
            name='users',
            field=models.ManyToManyField(help_text='可执行该路线调拨的用户', related_name='usable_routes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='route',
            name='warehouse',
            field=common.fields.ActiveLimitForeignKey(help_text='路线所属的仓库', on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='stock.Warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='procurementdetail',
            name='route',
            field=common.fields.ActiveLimitForeignKey(help_text='根据需求产生的位置以及指定的产品来源库位自动匹配的移动路线', on_delete=django.db.models.deletion.PROTECT, related_name='procurement_details', to='stock.Route', verbose_name='路线'),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='products',
            field=models.ManyToManyField(help_text='包裹可包装的产品', related_name='package_types', through='stock.PackageTypeProductSetting', to='product.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='packagetemplateproductsetting',
            name='type_setting',
            field=models.ForeignKey(help_text='包裹模板明细遵循的包裹类型', on_delete=django.db.models.deletion.CASCADE, related_name='template_settings', to='stock.PackageTypeProductSetting', verbose_name='包裹类型明细'),
        ),
        migrations.AddField(
            model_name='packagetemplate',
            name='package_type',
            field=common.fields.ActiveLimitForeignKey(editable=False, help_text='包裹模板的类型', on_delete=django.db.models.deletion.PROTECT, to='stock.PackageType', verbose_name='包裹类型'),
        ),
        migrations.AddField(
            model_name='packagetemplate',
            name='type_settings',
            field=models.ManyToManyField(help_text='包裹可包装的产品', related_name='package_templates', through='stock.PackageTemplateProductSetting', to='stock.PackageTypeProductSetting', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='packagenode',
            name='template',
            field=common.fields.ActiveLimitForeignKey(help_text='打包方法相关的包裹类型', on_delete=django.db.models.deletion.PROTECT, to='stock.PackageTemplate', verbose_name='包裹类型'),
        ),
        migrations.AddField(
            model_name='move',
            name='procurement_detail',
            field=models.ForeignKey(help_text='生成该移动的需求明细', on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='stock.ProcurementDetail', verbose_name='需求明细'),
        ),
        migrations.AddField(
            model_name='move',
            name='route_location_setting',
            field=models.ForeignKey(help_text='生成该移动的路线路径', on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='stock.RouteLocationSetting', verbose_name='需求匹配路径设置'),
        ),
        migrations.AddField(
            model_name='move',
            name='to_location',
            field=apps.stock.utils.LocationForeignKey(help_text='移动的结束库位', on_delete=django.db.models.deletion.PROTECT, related_name='in_moves', to='stock.Location', verbose_name='结束库位'),
        ),
        migrations.AddField(
            model_name='move',
            name='to_move',
            field=common.fields.ActiveLimitOneToOneField(blank=True, help_text='计划移动链的后续移动', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_move', to='stock.Move', verbose_name='后续移动'),
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=common.fields.ActiveLimitForeignKey(help_text='库位所属的区域', on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='stock.Zone', verbose_name='区域'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=set([('warehouse', 'usage')]),
        ),
        migrations.AlterUniqueTogether(
            name='routelocationsetting',
            unique_together=set([('route', 'sequence')]),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('initial_location', 'end_location', 'sequence')]),
        ),
        migrations.AlterUniqueTogether(
            name='procurementdetail',
            unique_together=set([('procurement', 'product', 'route', 'lot')]),
        ),
        migrations.AlterUniqueTogether(
            name='packagetypeproductsetting',
            unique_together=set([('package_type', 'product')]),
        ),
        migrations.AlterUniqueTogether(
            name='packagetemplateproductsetting',
            unique_together=set([('package_template', 'type_setting')]),
        ),
        migrations.AlterUniqueTogether(
            name='packagenode',
            unique_together=set([('parent_node', 'template')]),
        ),
        migrations.AlterUniqueTogether(
            name='move',
            unique_together=set([('procurement_detail', 'route_location_setting')]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('zone', 'x', 'y', 'z')]),
        ),
    ]
